sudo: false
dist: trusty
language: node_js

node_js:
- 7.4.0

env:
- CXX=g++-4.8

cache:
  directories:
  - node_modules

script: npm test

after_failure:
- tail -n 1000 /home/travis/build/davesag/github-labeller/npm-debug.log
